spring:
    datasource:
        url: jdbc:mysql://localhost:3306/search_engine?useSSL=false
        username: search_engine
        password: 9en2w0oc
    jpa:
        hibernate:
            ddl-auto: update
app:
    sites:
        -   url: http://www.playback.ru
            name: PlayBack.ru
#        -   url: https://volochek.life
#            name: Volochek.life
#        -   url: http://radiomv.ru
#            name: Radiomv.ru
#        -   url: https://ipfran.ru
#            name: Ipfran.ru
#        -   url: https://dimonvideo.ru
#            name: Dimonvideo.ru
#        -   url: https://nikoartgallery.com
#            name: Nikoartgallery.com
#        -   url: https://et-cetera.ru/mobile
#            name: Et-cetera.ru
#        -   url: https://www.lutherancathedral.ru
#            name: Lutherancathedral.ru
#        -   url: https://dombulgakova.ru
#            name: Dombulgakova.ru
#        -   url: https://www.svetlovka.ru
#            name: Svetlovka.ru
    user-agent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
    referrer: http://www.google.com
    web-interface: /admin